/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package testappclient0;

import java.util.ArrayList;
import java.util.List;
import org.cdms.domain.Permission;
import org.cdms.domain.User;
import org.cdms.ui.TableBinder;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JTableBinding;

/**
 *
 * @author Valery
 */
public class TableFrame extends javax.swing.JFrame {
    
    TableBinder master;
    TableBinder permissionDetail;
    
    BindingGroup userBindingGroup;
    ObservableList<User> userList;
    List<Permission> permission;
    JTableBinding jUserTableBinding;
    JTableBinding jPermissionTableBinding;    
    /**
     * Creates new form TableFrame
     */
    public TableFrame() {
        initComponents();
//        master = new TableBinder(jTable1_Users, userList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_Users = new javax.swing.JTable();
        jButton1_New_User = new javax.swing.JButton();
        jTextField1_LastName = new javax.swing.JTextField();
        dateField1 = new net.sf.nachocalendar.components.DateField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1_Permissions = new javax.swing.JTable();
        jButton1_New_Permission = new javax.swing.JButton();
        jTextField1_Permission = new javax.swing.JTextField();
        jButton1_Init_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        jTable1_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1_Users);

        jButton1_New_User.setText("new User");
        jButton1_New_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_New_UserActionPerformed(evt);
            }
        });

        jTextField1_LastName.setText("jTextField1");

        jTable1_Permissions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1_Permissions);

        jButton1_New_Permission.setText("new Permission");
        jButton1_New_Permission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_New_PermissionActionPerformed(evt);
            }
        });

        jTextField1_Permission.setText("jTextField1");

        jButton1_Init_.setText("init ");
        jButton1_Init_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Init_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1_Init_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1_New_User))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dateField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1_New_Permission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1_Permission))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_New_User)
                    .addComponent(jButton1_Init_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1_New_Permission)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_Permission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(253, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_New_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_New_UserActionPerformed
        userList.add(new User());
//                ObservableCollections.observableList(
//                        new ArrayList<User>());        
        
        //jTable1_Users.frepaint();
        //master.refresh();
        //userBindingGroup.unbind();
        //jUserTableBinding..setSourceObject(userList);        
        //userBindingGroup.bind();
        
        
         
        //jTable1_Users.getModel().
        
        //jTable1_Users.invalidate();
        //jTable1_Users.validate();
        //jTable1_Users.addRowSelectionInterval(0, userList.size()-1);
        //TableModelEvent e = new TableModelEvent(jTable1_Users.getModel(),
        //        TableModelEvent.HEADER_ROW);
        //tableBinding.refresh();
        //jTable1_Users.tableChanged(e);
        //jTable1_Users.addColumn(new TableColumn());
//        tableBinding.getBindingGroup().bind();
        userList.get(0).setLastName("Shyshkin");
        jTable1_Users.setRowSelectionInterval(userList.size()-1, userList.size()-1);        
        
    }//GEN-LAST:event_jButton1_New_UserActionPerformed

    private void jButton1_New_PermissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_New_PermissionActionPerformed
        int selUser = jTable1_Users.getSelectedRow();
        List<Permission> l = userList.get(selUser).getPermissions();
        if ( l == null ) {
            l = new ArrayList<Permission>();
            userList.get(selUser).setPermissions(l);
        }
        l.add( new Permission(5L,"simpleUser") );
        jTable1_Users.clearSelection();
        if ( selUser > 0  ) {
            jTable1_Users.setRowSelectionInterval(0, 0);        
        } else if ( selUser < userList.size() -1 ){
            jTable1_Users.setRowSelectionInterval(userList.size()-1, userList.size()-1);        
        }
        //jTable1_Users.setRowSelectionInterval(selUser+1, selUser+1);
        jTable1_Users.setRowSelectionInterval(selUser, selUser);        
        //userBindingGroup.unbind();
        //jUserTableBinding.setSourceObject(userList);        
        //userBindingGroup.bind();
        
    }//GEN-LAST:event_jButton1_New_PermissionActionPerformed

    private void jButton1_Init_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Init_ActionPerformed
        //userList = new ArrayList<User>();
        userList =  ObservableCollections.observableList(
                        new ArrayList<User>());        
        
        User u1 = new User();
        User u2 = new User();
        
        userList.add(u1);
        userList.add(u2);
        
        List<Permission> pList1 =  ObservableCollections.observableList(
                        new ArrayList<Permission>());        

        List<Permission> pList2 = ObservableCollections.observableList(
                        new ArrayList<Permission>());        
        Permission p1 = new Permission(100l, "admin");
        Permission p2 = new Permission(100l, "sys");        
        Permission p3 = new Permission(100l, "admin3");
        Permission p4 = new Permission(100l, "sys4");        
        pList1.add(p1);
        pList1.add(p2);
        pList2.add(p3);
        pList2.add(p4);
        u1.setPermissions(pList1);
        u2.setPermissions(pList2);  
        
        master = new TableBinder(jTable1_Users, userList);
        
        master.addColumn("id", long.class);
                master.addColumn("version", long.class);
                master.addColumn("permissions", List.class);                
                master.addColumn("firstName", String.class);
                master.addColumn("lastName", String.class);
                master.addColumn("userName", String.class);
                master.addColumn("password", String.class);
                master.bindTable();
        TableBinder child = master.addChild(jTable1_Permissions, "permissions");
        child.addColumn("permission", String.class);
        //ch.bindTable();
        
        //master.refresh();
        master.addTextFieldBinder(jTextField1_LastName, "lastName");
/*        Binding binding1 = Bindings.createAutoBinding(
                AutoBinding.UpdateStrategy.READ_WRITE,
                jTable1_Users,
                ELProperty.create("${selectedElement.lastName}"),
                jTextField1_LastName,
                BeanProperty.create("text"));
        
        tableBinding.addBinding(binding1);
        
        Binding binding2 = Bindings.createAutoBinding(
                AutoBinding.UpdateStrategy.READ_WRITE,
                jTable1_Permissions,
                ELProperty.create("${selectedElement.permission}"),
                jTextField1_Permission,
                BeanProperty.create("text"));
        tableBinding.addBinding(binding2);
        
        
        tableBinding.refresh();
        //userBindingGroup.unbind();        
        //userBindingGroup.bind();
*/        
        master.refresh();
        jTable1_Users.setRowSelectionInterval(0, 0);
        
        //jTable1.getTableHeader().getColumnModel().getColumn(1).setHeaderValue("V.M");                
        
        System.out.println("Val: " + userList.get(0).getPermissions().get(0).getPermission());

    }//GEN-LAST:event_jButton1_Init_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.sf.nachocalendar.components.DateField dateField1;
    private javax.swing.JButton jButton1_Init_;
    private javax.swing.JButton jButton1_New_Permission;
    private javax.swing.JButton jButton1_New_User;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1_Permissions;
    private javax.swing.JTable jTable1_Users;
    private javax.swing.JTextField jTextField1_LastName;
    private javax.swing.JTextField jTextField1_Permission;
    // End of variables declaration//GEN-END:variables
}
